### PR TITLE
Upgrade from 1.0.0-alpha to 1.0.0-beta

### PR DESCRIPTION
**Pull request by enragedginger**
This mostly consisted of changing the version numbers, but there were a couple of API changes too

### CODE REVIEW

**Comment by MrDallOca** [comment]
Oh, I think it's good to update build.boot too. @hswick uses boot if I'm not mistaking.

**Comment by enragedginger** [comment]
@MrDallOca I'm not sure what you're saying. I've updated both project.clj and build.boot. Did I miss something?

**Comment by MrDallOca** [comment]
Sorry, my bad! Didn't see you updated!

**Comment by hswick** [comment]
Nice. The record readers are on their end look a bit cleaner.

**Comment by hswick** [comment]
0.1.5 should be on clojars now

**Pull request merged**
