### PR TITLE
Issue #3: Added support for lein

### PR DESCRIPTION
**Pull request by MrDallOca**
Resolves issue #3.

Checkout [this](https://github.com/clojars/clojars-web/wiki/Pushing#leiningen-200) on using lein to deploy to clojars.

All four tests were satisfied:

Running tests using cider and lein
All tests succeeded

### CODE REVIEW

**Comment by hswick** [comment]
Hi! I appreciate the effort on this, but I'm not very interested in supporting both for development. At the end of the day I am the one responsible to maintain the codebase and I haven't used leiningen once since I've switched to boot. Nor do I plan on it. I include the nightlight IDE in the codebase so the barrier to contribution is very low. I'm not sure what your comment for deploying with lein is about, as I'm fully capable of deploying to clojars with boot.

**Comment by MrDallOca** [comment]
> I'm not sure what your comment for deploying with lein is about, as I'm fully capable of deploying to clojars with boot.

It's just that in the lein file there's no reference to clojars. So I just wanted to show how it's done using lein.

> Nor do I plan on it. I include the nightlight IDE in the codebase so the barrier to contribution is very low.

Unfortunately, I think that nightcode is probably not suitable for most of the developers, as it's much more preferable to use your editor of choice. I know cider supports boot, but by know I'm not able to install boot on my day to day machine cause I do not have admin access. Although my situation is unusual and there are some workarounds, it'd be way more comfortable to be able to use either boot or lein right after the clone and (IMO) it wouldn't be much of an issue updating the dependencies of both files (as you can see, project.lein is a small file).

FWIW, my intentions were good.

Thanks for the reply!

:)

**Comment by hswick** [comment]
If I came across a bit defensive I apologize but I have some very strong opinions on this. I also don't have a lot of patience catering towards emacs users, as emacs users don't generally cater to the rest of the community.

Since I will not be using lein, adding this file only creates more work for me with no gain.

That being said, I will merge this if you are willing to commit to maintain the lein support. FYI, I am planning on moving the datavec parts to a separate repo so you may end up having to maintain two different project.clj files.

**Comment by MrDallOca** [comment]
> I am planning on moving the datavec parts to a separate repo

If you're pulling it out as library, I wouldn't be required to support both lein and boot. In my understanding, it would make no difference at all.

>  I will merge this if you are willing to commit to maintain the lein support

I think the maintenance would consist about updating the dependencies and keeping them in sync with the codebase. In this regard, much of the work could be facilitated with good test covering. Under these circumstances, it seems for me that it'd be possible to maintain project.clj.

**Pull request merged**
